### ISSUE TITLE
Add a new task/event in Outlook Calendar API

### ISSUE THREAD

**Issue by MarouaneAyech** [MarouaneAyech/taskbot#2]
We want to explore Outlook Calendar API.
Particularly, we try to add a new task/event in the calendar.
Later, we need this operation. It will be integrated in rasa as a costumized action

**Comment by Samgalbi** [comment]
Bien reçu.

**Comment by MarouaneAyech** [comment]
@Samgalbi create a folder in the project root directory called outlook_calendar_api.
In thta folder, you implement a python script called **add_task.py**

**Comment by MarouaneAyech** [comment]
@Samgalbi Any progress ?

**Comment by MarouaneAyech** [comment]
@Samgalbi To update your local repo :
git fetch origin
git checkout 2-add-a-new-taskevent-in-outlook-calendar-api

**Comment by MarouaneAyech** [comment]
@Samgalbi create a new folder **outlook_calendar_api**
In which, you create the script **add_task.py**
This script connects to Graph API in order to add a new task in calendar

**Comment by MarouaneAyech** [comment]
@Samgalbi 
Please pull & review the code in your local repo as mentioned in associated pull request #3
